export const itemsData = [
    {
        id: "kids-1",
        name: "Sangria",
        description:
            "Dress with Gathering and Textured Crepe in Polka Dots for Girls",
        price: 14,
        category: "kids",
        image: "kids-1.jpg",
    },
    {
        id: "kids-2",
        name: "Mango Kids",
        description: "Boys Black Sustainable Jeans",
        price: 14,
        category: "kids",
        image: "kids-2.jpg",
    },
    {
        id: "kids-3",
        name: "Bella",
        description: "Girls Black & Golden Sequinned Fit & Flare Dress",
        price: 14,
        category: "kids",
        image: "kids-3.jpg",
    },
    {
        id: "kids-4",
        name: "H&M",
        description: "Girls Black Self-Design A-Line Midi Dress",
        price: 14,
        category: "kids",
        image: "kids-4.jpg",
    },
    {
        id: "kids-5",
        name: "Bhama",
        description: "Girls Orange & blue Printed Basic Two-Piece suit",
        price: 14,
        category: "kids",
        image: "kids-5.jpg",
    },
    {
        id: "kids-6",
        name: "Kiara",
        description: "Tie & Dye Light Blue T-Shirt",
        price: 14,
        category: "kids",
        image: "kids-6.jpg",
    },
    {
        id: "kids-7",
        name: "Generic",
        description: "Baby Slogan block Pullover and Jean Short",
        price: 14,
        category: "kids",
        image: "kids-7.jpg",
    },
    {
        id: "kids-8",
        name: "DISAUR",
        description: "Baby Boy Clothes Outfits",
        price: 14,
        category: "kids",
        image: "kids-8.jpg",
    },
    {
        id: "kids-9",
        name: "Levis",
        description: "Boys White Pure Cotton Slim Fit T-shirt",
        price: 14,
        category: "kids",
        image: "kids-9.jpg",
    },
    {
        id: "kids-10",
        name: "Kate",
        description: "Baby Girl Summer Ruffle Floral Dress",
        price: 14,
        category: "kids",
        image: "kids-10.jpg",
    },
    {
        id: "men-1",
        name: "Blue Jean Pant",
        description: "Men Slim Fit Mid-Rise Stretchable Jeans",
        price: 40,
        category: "men",
        image: "Men1.jpg",
    },
    {
        id: "men-2",
        name: "Black Jeans",
        description: "Men Black Slim Fit Mid-Rise Clean Look Stretchable Jeans",
        price: 30,
        category: "men",
        image: "men_2.jpg",
    },
    {
        id: "men-3",
        name: "Raymond",
        description: "Men Pure Cotton Slim Fit Micro Checked Formal Shirt",
        price: 20,
        category: "men",
        image: "men-3.jpg",
    },
    {
        id: "men-4",
        name: "Ecentric",
        description: "Men Cream-Coloured Solid Sustainable Eco-Friendly Lounge",
        price: 40,
        category: "men",
        image: "men_1.jpeg",
    },
    {
        id: "men-5",
        name: "Allen Solly",
        description: "Men Smart Slim Fit Formal Trousers",
        price: 40,
        category: "men",
        image: "men-5.jpg",
    },
    {
        id: "men-6",
        name: "Black Shirt",
        description: "Casual Shirt With Letters",
        price: 30,
        category: "men",
        image: "men-6.jpg",
    },
    {
        id: "men-7",
        name: "H&M",
        description: "Men White Slim Fit Easy-Iron Shirt",
        price: 20,
        category: "men",
        image: "Men_shirt1.jpg",
    },
    {
        id: "men-8",
        name: "DILLINGER",
        description: "Men Navy Blue Solid Pure Cotton T-shirt",
        price: 40,
        category: "men",
        image: "Men_tee.jpg",
    },
    {
        id: "men-9",
        name: "Brown Shirt",
        description: "Solid Button Up Shirt With Tee",
        price: 30,
        category: "men",
        image: "men-9.jpg",
    },
    {
        id: "men-10",
        name: "White and blue T-shirt ",
        description: "Best tee for men",
        price: 30,
        category: "men",
        image: "Men_tee3.jpg",
    },
    {
        id: "men-11",
        name: "UNDER ARMOUR",
        description:
            "Men White UA Sports Style LC SS Brand Logo Printed T-shirt",
        price: 50,
        category: "men",
        image: "Men_tee4.jpg",
    },
    {
        id: "men-12",
        name: "White shirt ",
        description: "White and Black Design shirt",
        price: 30,
        category: "men",
        image: "Men_shirt.jpeg",
    },
    {
        id: "women-1",
        name: "SASSAFRAS",
        description: "Brown Accordion Pleated Wrap top",
        price: 30,
        category: "women",
        image: "women-1.jpg",
    },
    {
        id: "women-2",
        name: "Mango",
        description: "Yellow Solid Empire Dress for Ladies",
        price: 60,
        category: "women",
        image: "women-2.jpg",
    },
    {
        id: "women-3",
        name: "Smarty Pants",
        description: "Mid-Rise Formal Pants for Ladies",
        price: 45,
        category: "women",
        image: "women-3.jpg",
    },
    {
        id: "women-4",
        name: "U&F",
        description: "Pink Maxi Gown in a Western Style",
        price: 30,
        category: "women",
        image: "women-4.jpg",
    },
    {
        id: "women-5",
        name: "YK",
        description: "Girls Black Ribbed A-Line Dress",
        price: 40,
        category: "women",
        image: "women-5.jpg",
    },
    {
        id: "women-6",
        name: "Athena",
        description: "Blue Washed Regular Fit Jeans for Women",
        price: 45,
        category: "women",
        image: "women-6.jpg",
    },
    {
        id: "women-7",
        name: "Sera",
        description: "Maxi Dress in Blue Floral Chiffon Tiered",
        price: 45,
        category: "women",
        image: "women-7.jpeg",
    },
    {
        id: "women-8",
        name: "OXO",
        description: "Women's Self-Design Wrap Crop Top in Cream",
        price: 20,
        category: "women",
        image: "women-8.jpg",
    },
    {
        id: "women-9",
        name: "Levis",
        description:
            "Stretchable Navy Blue Skinny Fit Mid-Rise Jeans for Women",
        price: 35,
        category: "women",
        image: "women-9.jpg",
    },
];
